name: Deploy to Hostinger

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Deploy to Hostinger
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: in-mum-web1672.main-hosting.eu
        username: u698056983
        key: ${{ secrets.HOSTINGER_SSH_KEY }}
        script: |
          # Backup current files
          if [ -d "public_html_backup" ]; then
            rm -rf public_html_backup
          fi
          if [ -d "public_html" ]; then
            mv public_html public_html_backup
          fi
          mkdir public_html
          
    - name: Upload files
      uses: appleboy/scp-action@v0.1.4
      with:
        host: in-mum-web1672.main-hosting.eu
        username: u698056983
        key: ${{ secrets.HOSTINGER_SSH_KEY }}
        source: "dist/*"
        target: "public_html/"
        
    - name: Set permissions
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: in-mum-web1672.main-hosting.eu
        username: u698056983
        key: ${{ secrets.HOSTINGER_SSH_KEY }}
        script: |
          chmod 755 public_html/
          chmod 644 public_html/*.html
          chmod 644 public_html/*.css
          chmod 644 public_html/*.js
          echo "Deployment completed successfully!"
